version: 2
updates:
    -   package-ecosystem: "composer"
        directory: "/"
        schedule:
            interval: "daily"
        assignees:
            - "kzmshx"
        reviewers:
            - "kzmshx"
        labels:
            - "composer-update"
        versioning-strategy: "widen"
